# Schema reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

# name: $(Rev:r)_$(SourceBranchName)_$(Build.SourceVersion)_$(Build.SourceVersionMessage)

variables:
  buildDockerfile: './Dockerfile'

pool:
  vmImage: ubuntu-latest

# Run on every push
# trigger:

# Run on every pull request
# pr:

stages:
  - stage: DEV_CI
    displayName: DEV CI
    jobs:
    - job: UseDotnet5Job
      displayName: Install .NET 5
      steps:
        - task: UseDotNet@2
          displayName: Install .NET 5
          inputs:
            packageType: sdk
            version: 5.0.x
    - job: BuildJob
      displayName: Build solution
      steps:
      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: build
          arguments: --configuration Release
      dependsOn: UseDotnet5Job
    - job: TestJob
      displayName: Test solution
      steps:
        - task: DotNetCoreCLI@2
          displayName: dotnet test
          inputs:
            command: test
            arguments: --configuration Release
      dependsOn: BuildJob

  # - stage: Build
  #   displayName: Build stage
  #   jobs:
  #   - job: BuildDockerImageJob
  #     steps:
  #     - task: Docker@2
  #       displayName: Build project as Docker image
  #       inputs:
  #         command: 'build'
  #         Dockerfile: $(buildDockerfile)